main: com.cavetale.mapload.MapLoadPlugin
name: MapLoad
version: 0.1
api-version: 1.13
description: Load each chunk of a world once.
author: StarTux
website: https://cavetale.com
depend: []
softdepend: []
commands:
  mapload:
    aliases: []
    description: MapLoad Command
    permission: mapload.mapload
    usage: /mapload
permissions:
  mapload.mapload:
    description: Use /mapload
    default: op
